# Generated by Django 2.0.13 on 2019-08-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, upload_to="{% media 'images/' %}"),
            preserve_default=False,
        ),
    ]
