# Generated by Django 2.0.13 on 2019-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190809_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
