# Generated by Django 2.0.13 on 2019-08-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
