# Generated by Django 2.0.13 on 2019-08-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product1',
        ),
    ]
