# Generated by Django 2.0.13 on 2019-08-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190810_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
