# Generated by Django 2.0.13 on 2019-08-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_product2_product3_product4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='product2',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='product3',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='product4',
            name='published_date',
        ),
    ]
