# Generated by Django 2.0.13 on 2019-08-13 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190813_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='product2',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='product3',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='product4',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'tif'])]),
        ),
    ]
